### ISSUE TITLE
PHP Fatal errors when assigning any supertask

### ISSUE THREAD

**Issue by snuuzftw** [s3inlc/hashtopussy#266] opened 2017-08-17 11:18 UTC
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Hashtopussy: 0.4.2
Client: 0.43.19
Hashcat: 3.6.0

When I'm assigning a supertask to any of my agents, the API server responds with a 500 Internal Server Error for the {"action":"task","token":"TTprXwB9oI"} request.

Checking the apache error.log on why it's crashing, there's TONS of these messages:
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/hashtopussy/inc/API.class.php:956\nStack trace:\n#0 /var/www/html/hashtopussy/api/server.php(74): API::getTask(Array)\n#1 {main}\n  thrown in /var/www/html/hashtopussy/inc/API.class.php on line 956

hashtopussy.exe debug shows:
Using legacy STATUS codes
Getting task
{"action":"task","token":"tCiRp22SCz"}

Once I cancel the assignment, 
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent

So my guess is it's getting stuck in a loop trying to get a task hundreds of times per second.

The subtasks don't seem to matter - it affects all supertask assignments. It can be either be one simple brute-force attack or a number of brute-force and huge dictionary attacks.

Am I doing something wrong?

**Comment by s3inlc** [comment] 2017-08-17 11:34
I cannot reproduce your error with the given information.
But I identified the problematic situation which must have caused this error. I changed the code to check for a null object before accessing it's values. Can you please try with the newest code if the problem still persists?

Additionally, I recommend to use the latest client (version 0.45.8).

**Comment by snuuzftw** [comment] 2017-08-17 13:03
Hi,

I've upgraded to the newer version & using the latest client - no errors. However, now I'm not able to run any tasks (they're not being sent to the agents):

Client Version 0.45.8
Checking for client updates
{"action":"update","type":"csharp","version":"0.45.8"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Linux
Existing token found
{"action":"login","token":"tCiRp22SCz"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"tCiRp22SCz","force":0}
Hashcat version v3.6.0 found
Using legacy STATUS codes
Getting task
{"action":"task","token":"tCiRp22SCz"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
Getting task
{"action":"task","token":"tCiRp22SCz"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent


Tasks are set though:

![image](https://user-images.githubusercontent.com/11502721/29413449-151e6a40-8365-11e7-926a-cbf1f5dc48b4.png)

![image](https://user-images.githubusercontent.com/11502721/29413511-47646892-8365-11e7-9227-13b550eb1fbf.png)


Some additional info - the error.log also contains some notices regarding AgentIds being undefined (which is weird seen as how they clearly have ids):

![image](https://user-images.githubusercontent.com/11502721/29413573-7f06374e-8365-11e7-9ff4-c3bf786c6c7d.png)

**Comment by s3inlc** [comment] 2017-08-17 13:06
Can you give me some informations about the task?

**Comment by snuuzftw** [comment] 2017-08-17 13:15
Of course:

![image](https://user-images.githubusercontent.com/11502721/29414043-2a126e4a-8367-11e7-95cb-4f84af3607a8.png)

![image](https://user-images.githubusercontent.com/11502721/29414067-437352aa-8367-11e7-9402-a7e247f197d8.png)

**Comment by s3inlc** [comment] 2017-08-17 13:21
The tasks you sent screenshots of, are all preconfigured tasks. Is it possible to have the list of the current tasks then I can maybe tell more. (If you need to black out anything, feel free)

**Comment by snuuzftw** [comment] 2017-08-17 13:37
Sorry, I deleted all the old (normal) tasks I had prior to upgrading. However, I've created a new task and it seems to be working:

![image](https://user-images.githubusercontent.com/11502721/29414695-3e21d518-8369-11e7-81e2-7eb5094219d7.png)

The problem is still only with supertasks, they're not getting assigned:

![image](https://user-images.githubusercontent.com/11502721/29414875-cc2574d2-8369-11e7-901a-78529b1484c5.png)

The normal task is running fine, however, the supertask is not getting sent to the agent.

![image](https://user-images.githubusercontent.com/11502721/29414899-e7ab1fa4-8369-11e7-84bf-f3c0c6f6f6aa.png)

![image](https://user-images.githubusercontent.com/11502721/29414942-0656336c-836a-11e7-81a5-2da964b59183.png)

If I try to assign it in the window above, I get a PHP notice:
PHP Notice:  Undefined index: agentId in /var/www/html/hashtopussy/agents.php on line 38, referer: http://172.27.0.59/hashtopussy/tasks.php?id=24

And after a while of doing nothing, there's LOADS of PHP fatal errors afterwards:
PHP Fatal error:  Uncaught Error: Call to a member function getFormat() on null in /var/www/html/hashtopussy/inc/Util.class.php:606\nStack trace:\n#0 /var/www/html/hashtopussy/inc/Util.class.php(436): Util::checkSuperHashlist(NULL)\n#1 /var/www/html/hashtopussy/inc/Util.class.php(489): Util::agentHasAccessToTask(Object(DBA\\Task), Object(DBA\\Agent))\n#2 /var/www/html/hashtopussy/inc/API.class.php(918): Util::taskCanBeUsed(Object(DBA\\Task), Object(DBA\\Agent))\n#3 /var/www/html/hashtopussy/api/server.php(74): API::getTask(Array)\n#4 {main}\n  thrown in /var/www/html/hashtopussy/inc/Util.class.php on line 606

**Comment by snuuzftw** [comment] 2017-08-18 09:15
Hi, 

I played around a bit and noticed that the tasks were not CPU only while the nodes were - so I changed CPU only on my nodes to no.

I then enabled mysql logging and noticed that the queries for getting tasks for a supertask (getBestTask in Util.class.php) return no results, mainly due to this:

WHERE priority>'0'

so I swapped the > to >= in that function: 

$priorityFilter = new QueryFilter(Task::PRIORITY, $priority, ">");
$priorityFilter = new QueryFilter(Task::PRIORITY, $priority, ">=");

Everything seems to be working now. I guess it must have been due to my my supertask or tasks (not sure) having 0 priority.

**Comment by s3inlc** [comment] 2017-08-18 09:30
Glad you were able to resolve some issues yourself. We are aware that the wiki is lacking of some documentation how to use certain features and what has to be considered.

CPU only:
If the agent does not send a typical GPU string as devices (containing nvidia, amd, etc.) the agent is automatically considered as CPU only (in your case this happened because of the vm). CPU only agents also will only get CPU only tasks. This features was introduced to be able to separate tasks (e.g. with bcrypt) which are better to run on CPU from the other ones.

Priority:
Your hack is correct, but the idea was not to do it that way. Already in Hashtopus, tasks were automatically assigned to agents when they had a priority >0. When you wanted to make the assignment manually, the priority could be kept on 0 and then the assignments can be done directly on the task detail page. So if you want to have it done automatically, all the tasks you want to have done need to have a priority > 0.
In the special case of Supertasks, the Supertasks priority is essential for the order of the supertask inside the other normal tasks. Inside the Supertask the priorites only set in which order the subtasks are executed.

I hope these explanations helped to clarify some things.

**Comment by snuuzftw** [comment] 2017-08-18 10:02
Yeah, it is slightly odd that its showing vmware svga as the gpu - the vms have a couple of nvidia gpus each.

But that definitely cleared things up, thanks!

**Comment by winxp5421** [comment] 2018-01-21 04:34
house cleaning, If you still need help please re-open.

**Closed by winxp5421** 2018-01-21 04:34 UTC
