### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by kawuum** [s3inlc/hashtopussy#249] opened 2017-08-02 10:32 UTC
Hashtopussy Server Version: 0.3.2

Hashtopussy Client Version: 0.43.13

Hashcat Version: 3.6.0

Task command I am running: 
-a0 #HL# -r dive.rule dictionary

The dictionary contains exactly 2.5 Million entries. [Edit says: The rule is the dive rule shipped with hashcat.] The benchmark-value for the hashtopussy client is: 0.00031992033856083. The benchmark-type is Runtime Benchmark. 

I noticed, that the speed running this task on hashtopussy is significantly slower than using hashcat directly. The machine I am using contains multiple Graphics Cards. The performance is as follows:

Hashcat directly: 791 kH/s
Hashtopussy: 67000 H/s

I tried to debug the problem by my self by checking the hashcat command which is issued by hashtopussy (i.e. ps aux | grep hashcat). It turned out, that hashtopussys command contains the following two parameters:
-s 0 -l 6014
meaning the currently processed work item contains the dictionary lines from 0 - 6014 if I understand correctly.

Manually changing only the -l parameter to: -l 6014 has a severe positive impact on performance: 528 kH/s. Using -l 601400: 758 kH/s. Not specifying the -l parameter parameters shows the same performance as running hashcat directly.

So my conclusion is that this probably has something to do with using a relatively small dictionary together with a big rule.  

Do you have an advice about how to deal with this issue?

Thanks in advance for your Help, much appreciated!

**Comment by s3inlc** [comment] 2017-08-02 18:47
In most cases when this performance difference occurs, the chunk sizes are too small for Hashcat and therefore the GPUs are not fully used. Often this is caused by either a wrong benchmark result or just in some edge cases depending on what the task should do.

What you gave as example with -s 0 -l 6014 does not say that it does these lines on the dictionary. These values are keyspace values which are not exactly the number of combinations, only dependent of it. 

But nevertheless a chunk size of 6014 is too small (as long as we are not talking about a very slow algorithm) and therefore the speed is too low. Did you try to do the benchmark again? Does it produce similar results?

If this still happens, you can manually adjust the benchmark result. For example, if you want to have the chunk size increased by the factor 2 you can multiply the benchmark result also with 2 and set this. As showing with your example, you could multiply it with 100 and then look if it runs better then.

**Comment by winxp5421** [comment] 2018-01-21 04:28
Closing please reopen if you still need help

**Closed by winxp5421** 2018-01-21 04:28 UTC
