### ISSUE TITLE
Fatal Error ! Database connection failed

### ISSUE THREAD

**Issue by carl487** [s3inlc/hashtopussy#183] opened 2017-04-27 07:43 UTC
hello,

after following the instalation video and wiki, i cant install the new version hashtopussy
when i click the button "Continue" on instalation page, i get following error "Fatal Error ! Database connection failed"

previous version worked fine for me (after following your tutorials)
did something change ? thanks for response

Server version: v0.3.2
System: Tried Ubuntu server 16.10 and 17.04

**Comment by s3inlc** [comment] 2017-04-27 08:28
Thanks for the notification about this issue. There was a small mistake in the install script after the update to version 0.3.2 which made it skipping the form for filling in the database details.

Please just pull the new code from master now and the installation should run then without problems. If the issue is fixed, please close it.

**Comment by carl487** [comment] 2017-04-27 10:57
Thanks for the fast response !

Its working now, but i had to reinstall the system, because nothing else worked, no idea why (using ubuntu server 16.10 now, 17.04 didnt work for me)

great job ;)

**Closed** 2017-04-27 10:58 UTC
Labels: bug
