### ISSUE TITLE
$CONN is not defined at first install

### ISSUE THREAD

**Issue by matlink** [s3inlc/hashtopussy#260] opened 2017-08-12 12:12 UTC
##### Your current Server version located at the bottom of any hashtopussy webpage.
0.4.2

#### Describe your problem in as much detail as possible " It's broke " is not a description.
When following https://github.com/s3inlc/hashtopussy/wiki/Server-Prerequisites for installation, fetching http://localhost/hashtopussy/install/index.php returns a PHP error telling $CONN is not defined (from dba/init.php file). To bypass it, I temporarily removed "define"s at the beginning of this file while setting DB parameters, then re-enabled them.

**Comment by NullPatrol** [comment] 2017-08-12 13:18
From what I could see, 'root' or passwordless mysql users are not supported.
A solution is to create a secondary mysql account with access to the desired database.

`GRANT ALL PRIVILEGES ON hashtopussy.* TO 'hashtopussy'@'localhost' IDENTIFIED BY 'secretpassword';
FLUSH PRIVILEGES;`

**Comment by matlink** [comment] 2017-08-12 16:05
This has nothing to do with my issue. `$CONN not defined` happens before setting database connection.

**Comment by s3inlc** [comment] 2017-08-12 17:17
did you upgrade from an earlier version? Because from 0.3.2 to 0.4.0 the way how the database connection details are stored changed. The credentials are now stored in `inc/db.php` (like in the template `inc/db.template.php` and not in the load.php file anymore.

If it's from a clean new install, please check if the file `inc/db.php` is present. Maybe when the www-user didn't have write permissions in this folder he couldn't create this file during installation.

**Comment by matlink** [comment] 2017-08-12 18:00
Well it is before installation, in the index.php which require_once inc/load.php which loads dba/init.php which has $CONN variable

**Comment by s3inlc** [comment] 2017-08-12 18:20
I see what you mean. But this does not throw an error but a warning, right?

**Comment by matlink** [comment] 2017-08-12 18:23
Well it depends on the PHP config I think, my own stopped after errors.

**Comment by s3inlc** [comment] 2017-08-12 18:24
ok, I'll fix this

**Comment by s3inlc** [comment] 2017-08-12 18:28
Can you please test if the issue is fixed for you now and close this if it's working.

**Comment by winxp5421** [comment] 2018-01-21 04:27
I believe this was fixed. Closing this issue. Please reopen if this is still relevant

**Closed by winxp5421** 2018-01-21 04:27 UTC
