### ISSUE TITLE
Supertask is not working on 0.4.2

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#292] opened 2017-10-21 14:49 UTC
**Your current Server version located at the bottom of any hashtopussy webpage.**

```
Hashtopussy: commit c66ec8f branch master 0.4.2
Hashcat 3.6.0
```

**Debug output from the client by running "hashtopussy.exe debug"**
```
c:\Users\d2\Downloads\hp_lin>hashtopussy.exe debug
Client Version 0.43.19
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.19"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"eXkYiIKoLH"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"eXkYiIKoLH","force":0}
Hashcat version v3.6.0 found
Getting task
{"action":"task","token":"eXkYiIKoLH"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
```
**Describe your problem in as much detail as possible**

I am trying to assign supertask to agents and they do not see it. I have two [pre-configured tasks](https://prnt.sc/h06k39). I have also created [supertask](https://prnt.sc/h06l43) from them and assigned to list. Nothing is happening, agents do not see any task to work on. When I visit task details I see [this](https://prnt.sc/h06lmf).

What could be wrong here?

**Comment by s3inlc** [comment] 2017-10-21 16:01
Can you post a screenshot of your task overview. I think maybe there is something set wrong with the priorities.

**Comment by d2-d2** [comment] 2017-10-21 16:04
@s3inlc sure, here it is: https://prnt.sc/h07fb5 (since when supertasks are dark-grey on that list? I've noticed that recently).

**Comment by s3inlc** [comment] 2017-10-21 16:06
Sorry, I was not clear enough, the expanded view would be the best, so I can see also the subtasks of the supertask.

They just have a grey background to make them better visible, so it's easier to see which tasks are supertasks.

**Comment by d2-d2** [comment] 2017-10-21 16:07
Hmm I think I've already posted details here: https://prnt.sc/h06lmf but pls let me know if it is not what you are still looking for :)

**Comment by s3inlc** [comment] 2017-10-21 16:12
The problem is, that in the supertask details I don't see the subtasks themselves. The subtasks can be shown/hidden with the blue button on the tasks overview.

If I can see correctly, all your tasks have the priority 0, is that correct?`
In case the supertask's priority is 0 and you assigned the agents manually, you need to make sure that the subtasks have a priority higher than 0, otherwise the agents won't get assigned to a subtask to work on.
If you want to have all assigning manual, you need to directly assign an agent to a specific subtask.

**Comment by d2-d2** [comment] 2017-10-21 16:16
Oh my, okay... That worked. I've just set priority as instructed and both agents picked new tasks without problems. Thanks @s3inlc for your help :)

**Closed** 2017-10-21 16:22 UTC
