### ISSUE TITLE
Large Chunk sizes are randomly issued.

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopussy#162] opened 2017-04-10 19:02 UTC
Hi,

whats this loop? This agent was running normally, now it stopped and it was like this
hashcat64.exe -b not error
Loop:
Getting chunk...
Server requsted the client benchark this task for 30 seconds
Getting chunk...
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
Server requsted the client benchark this task for 30 seconds
Getting chunk...
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
Server requsted the client benchark this task for 30 seconds

is necessary attach any screen?

**Comment by pccheck** [comment] 2017-04-11 11:07
other error in loop
[agents.pdf](https://github.com/s3inlc/hashtopussy/files/912943/agents.pdf)
[taskdetails.pdf](https://github.com/s3inlc/hashtopussy/files/912944/taskdetails.pdf)


Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\8.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\8.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\8.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload
ERROR
Chunk was aborted!
Writing any cracks in queue to file C:\NVIDIA\hashlists\8.cracked
Nenhum processo associado a este objeto.
Error processing packet for upload

**Comment by winxp5421** [comment] 2017-04-11 11:45
Need all the client debug.

**Comment by pccheck** [comment] 2017-04-11 12:05
C:\NVIDIA>hashtopussy.exe -debug
Client Version 0.43.12
Checking for client updates
You are using the latest client version
System is Windows
Existing token found
Logged in to server
Hashcat version v3.5.0 found
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
^C

**Comment by winxp5421** [comment] 2017-04-11 12:15
Are you sure the agent is Active

**Comment by winxp5421** [comment] 2017-04-11 12:16
its "hashtopussy.exe debug" not hashtopussy.exe -debug

**Comment by pccheck** [comment] 2017-04-11 12:31
see results

Getting chunk...
{"action":"chunk","token":"hSqUbe54hN","taskId":12}
{"action":"chunk","response":"SUCCESS","status":"fully_dispatched"}
Getting task
{"action":"task","token":"hSqUbe54hN"}
{"action":"task","response":"SUCCESS","task":12,"attackcmd":"-a0 #HL# rockyou.txt -r rockyou-30
000.rule","cmdpars":" --hash-type=2500","hashlist":8,"bench":30,"statustimer":5,"files":["rocky
ou-30000.rule","rockyou.txt"],"benchType":"run","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"hSqUbe54hN","hashlist":8}
{"action":"hashes","response":"SUCCESS","data":"SENQWAQAAAACBlRyb2phbgAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAr+JSo3BdE0e49EbzIYs7V54VC7rYB5rL9GSYOW6jPx4PN9vZceg39ZEklnSht51d3LrKfekS7RSfQ8NybMjtf
kiBFqEgimz6WrSS1JwOA3uNn9GXVESy\/d8oZ4\/eQABAwB1AgEKAAAAAAAAAAAACLMjtfkiBFqEgimz6WrSS1JwOA3uNn9
GXVESy\/d8oZ4\/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYwFAEAAA+sAgEA
AA+sBAEAAA+sAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA"}
Getting chunk...
{"action":"chunk","token":"hSqUbe54hN","taskId":12}
{"action":"chunk","response":"SUCCESS","status":"fully_dispatched"}

**Comment by winxp5421** [comment] 2017-04-11 12:32
your task is fully dispatched to other agents

**Comment by pccheck** [comment] 2017-04-11 12:37
s this normal? This agent can no longer be availed in this task?

**Comment by winxp5421** [comment] 2017-04-11 12:43
i have a feeling because you played with benchmark sizes some agents have HUGE chunks of the task. So yes this is normal.

**Comment by blazer2x** [comment] 2017-04-11 14:20
This is possibly a server-side bug. The server should not be dispatching a fully dispatched task??
Not sure if this is intended. Flagging for sein to review.

**Comment by r3ddi** [comment] 2017-04-11 16:28
looks like the same problem that i have too:

4 Clients cracking a WPA / WPA2 Hashlist with mask ( -a ?d?d?d?d?d?d?d?d?d?d )
After some hours of cracking hashtopussy give one client all left chunks to crack. i have test this multiple time. Its not client specific.

Result is that no Client can assign to this task because all chuncks dispached.
Testet with 3.40 and 3.5.0 on all Clients (OS of the Clients is Mixed ( Linux & OSX ).

Ive abort the Job and tried to reset it, but the dispatched keyspaces will not be released again so no of the other 3 Clients can crack this task anymore

Hope it helps, i have added some screenshots

<img width="1191" alt="bildschirmfoto 2017-04-11 um 18 13 29" src="https://cloud.githubusercontent.com/assets/23745927/24919639/a3218222-1ee4-11e7-9f06-4be63c01091f.png">
<img width="1201" alt="bildschirmfoto 2017-04-11 um 18 13 21" src="https://cloud.githubusercontent.com/assets/23745927/24919641/a348ffe6-1ee4-11e7-9aab-cdf2552a9b62.png">
<img width="1252" alt="bildschirmfoto 2017-04-11 um 18 12 59" src="https://cloud.githubusercontent.com/assets/23745927/24919640/a34550da-1ee4-11e7-8074-09a9c0022bd9.png">

**Comment by winxp5421** [comment] 2017-04-11 16:42
Hmm, ok then there is certainly an issue with this rather strange that the server suddenly sends a huge chunk for no reason.

**Comment by soxrok2212** [comment] 2017-04-11 16:44
This actually happened to me completely randomly yesterday. Out of the blue, 70% of a 26^8 keyspace on WPA was issued to one agent. Didn't touch the benchmarks. My rough solution was to just create a new task and skip the first 30% that had already finished.

**Comment by s3inlc** [comment] 2017-04-11 16:53
Which benchmark type was used?

**Comment by winxp5421** [comment] 2017-04-11 16:55
speed test

**Comment by soxrok2212** [comment] 2017-04-11 16:55
Originally Speed Test. After that I switched to Runtime Benchmark as one of the agents runs older HD 5900 series cards (Speed Test caused issues for it). I did not have the problem with Runtime Benchmark.

**Comment by s3inlc** [comment] 2017-04-11 16:56
@r3ddi could you provide me the benchmark values for your agents which they had on this task?
or @soxrok2212 do you have the benchmark values and the chunk sizes you had on your task then?

**Comment by soxrok2212** [comment] 2017-04-11 16:58
I don't have the benchmark values, unfortunately.

**Comment by pccheck** [comment] 2017-04-11 17:11
I use runtime, speed very bad values benchmark, my tasks is running now
If I can help with some data.

**Comment by r3ddi** [comment] 2017-04-11 17:17
@winxp5421 

I didnt have the Benchmark values anymore, but i purged the same task and can provide the current running Benchmark Values for the 4 Test Clients.

Client1: 8192:113963.92
Client2: 5632:132696.13
Client3: 8192:113521.87
Client4: 8192:114010.47

Hope this helps

**Comment by s3inlc** [comment] 2017-04-11 17:20
Ok thanks, this definitely should help me. I'll check if there is a calculation problem as soon as possible.

**Comment by pccheck** [comment] 2017-04-11 17:28
details my task
[taskdetails.pdf](https://github.com/s3inlc/hashtopussy/files/914164/taskdetails.pdf)

**Comment by s3inlc** [comment] 2017-04-11 17:32
Just to be sure that it's definitely not an overflow issue at some point, are you running PHP on 64-bit on the servers?

**Comment by pccheck** [comment] 2017-04-11 17:49
yes, my server is Ubuntu 16.10 x64

**Comment by r3ddi** [comment] 2017-04-11 17:52
Same for me:

Debian 8 x64
PHP 7.0.17-1

**Comment by pccheck** [comment] 2017-04-11 18:00
PHP 7.0.15-0ubuntu0.16.10.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.10.4, Copyright (c) 1999-2017, by Zend Technologies
Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by s3inlc** [comment] 2017-04-11 18:01
Ok thanks, that's good. 

@r3ddi If you have some time, would it be possbile to run the same task again and see if it happens exactly at the same chunk?

**Comment by soxrok2212** [comment] 2017-04-11 18:10
64-bit here as well.. Would take a long time for me to get at the same chunk again so I am unable to do that at the current time as well.

**Comment by winxp5421** [comment] 2017-04-11 18:15
Alright, my suggestion is for everyone to keep a close eye on their chunk sizes. If any chunk gets issued that may not seem right Please post As much information as you can in this issue thread. Benchmarks, chunk size, previous chunk history, etc. I would rather have to much info than not enough.

**Comment by r3ddi** [comment] 2017-04-11 18:54
@s3inlc 

Task is running again, i will post new information if the problem pop up again.

**Comment by r3ddi** [comment] 2017-04-11 19:16
@s3inlc i added some more Agents an the same "purged"  task to get faster to the chunk where in the last run one client get a too Large Chunk size.

This time it didnt makes any Problem but if i remember correctly, all my runs on this task in the last 4 days ended with this problem at a differen Chunk range.

I let the Task running and will update if there any news.

here an updated screenshot from the current running task.

<img width="886" alt="bildschirmfoto 2017-04-11 um 21 14 41" src="https://cloud.githubusercontent.com/assets/23745927/24926485/ffdcc924-1efb-11e7-84ae-bbae7161fb0f.png">

**Comment by s3inlc** [comment] 2017-04-11 19:37
Thanks a lot for your information and letting it running :)

I just hope it's not some random stuff happening as this might get very difficult to identify..

**Comment by r3ddi** [comment] 2017-04-12 19:11
Hi Again,

Today i completely reinstalled all Agents und Hashtopussy Server
But the Problem comes again after some time.

This time was the big chunk Client a Macbook Pro the Benchmark Value of the problematic large chunck is 122880 without any seperator ( : ) normally it is 61440:327748.72 or so.

Keyspace size: 1000000000
Keyspace dispatched: 1000000000 (100.00%)
Keyspace searched: 15937024 (1.59%)


Screen vom the task:
![Uploading Bildschirmfoto 2017-04-12 um 21.00.17.png…]()

**Comment by s3inlc** [comment] 2017-04-13 09:57
Thanks a lot for testing it. I identified some problematic code where there got a benchmark set without caring about which benchmark type it was.

@r3ddi Could you please checkout this branch: https://github.com/s3inlc/hashtopussy/tree/bugfix/issue-162 and test if the problem is gone or still present?

**Comment by r3ddi** [comment] 2017-04-13 10:39
sure, will try it today.

**Comment by r3ddi** [comment] 2017-04-13 18:32
@s3inlc  looks like the changes in "AgentHandler.class.php" fixed the problem.

All the day the task runs perfect ! I never searched so many Keyspace without a problem.
i let it running, but it looks really good.

**Comment by s3inlc** [comment] 2017-04-13 18:33
Wohoo, great. Thanks a lot for testing!

**Comment by r3ddi** [comment] 2017-04-13 18:33
👍

**Comment by winxp5421** [comment] 2017-04-13 18:33
This is fantastic! Please keep a close eye on your workers! wohoo

**Comment by r3ddi** [comment] 2017-04-13 18:35
@winxp5421  sure the agents working :) , if i see any problems with large chunks i let u know it.

**Comment by s3inlc** [comment] 2017-04-13 18:37
Fix is merged into master

**Closed by s3inlc** 2017-04-13 18:37 UTC
Labels: bug
