### ISSUE TITLE
"Invalid query" when trying to connect to the server from the C# client

### ISSUE THREAD

**Issue by lavanoid** [s3inlc/hashtopussy#327] opened 2018-02-10 10:32 UTC
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.4.3
Current Client version
C# version 0.50.2
Your current Hashcat version
4.0.1
The exact task command you are trying to run.
I've opened up the hashtopussy.exe program and attempted to connect to the server, with no luck.
Debug output from the client by running "hashtopussy.exe debug"
![image](https://user-images.githubusercontent.com/4705167/36061100-4c0b4690-0e4d-11e8-9ab0-73fac9c92edd.png)

Describe your problem in as much detail as possible " It's broke " is not a description.
As the above picture shows, I've tried connecting to my hashtopussy server but I've not had any good luck with it. The webserver is hosted on port 8443 and is using HTTPS. There is also a redirect on port 80 that enforces HTTPS, though I HAVE been specifying HTTPS and port 8443 from within the client program and I just keep getting an "Invalid query" error message.

Output of server.php when I visit with a browser:

```{"action":"INV","response":"ERROR","message":"Invalid query!"}```

This is being hosted on a Raspberry Pi using Arch Linux and I'm pretty sure I have all the necessary dependencies installed.

**Comment by s3inlc** [comment] 2018-02-16 11:12
Client versions starting from 0.50.x are designed for the new version of hashtopussy which is in progress and will be released soon (0.5.0). The newer versions of the c# client do not work correctly with the 0.4.3 or older server versions.
So you either can upgrade to the 0.5.0 version (which is in the dev branch currently) or use the latest C# agent before version 0.50.x

**Comment by lavanoid** [comment] 2018-02-16 22:05
Okeydoke. I should probably open another issue for this but I'll put it here as well - I installed the dev branch onto my Raspberry Pi and made sure I cleared the SQL database and the initial setup would keep saying that everything was configured, but throw out errors when clicking the continue button (this was a few days ago).

**Comment by winxp5421** [comment] 2018-02-16 22:12
What kind of errors where appearing?
Verify the SQL tables are actually created.
Without more info im not sure how much more assistance we can give you with your second issue.

**Comment by winxp5421** [comment] 2018-02-16 22:15
Also, in the past we have seen a lot of people have issues when running hashtopussy on a raspberry pi. Mainly because they are running a 32 bit operating system. 

I dot believe this is causing you current issue!
however,
Just as a preventative measure for a future problem please verify you are indeed running 64 bit php. There is a script for checking located here: https://github.com/s3inlc/hashtopussy/wiki/Frequent-Problems

**Comment by lavanoid** [comment] 2018-02-16 22:22
Thanks for the tips. I don't know why but a few days ago after trying 0.4.3, version 5.0 would just say that the installation has completed, even though I hadn't specified any credentials and clicking continue would show some error messages (unfortunately I did not document them). I made sure the database existed and that all the configuration was erased from 0.4.3 and it was still having issues.

Not sure what has happened just now but it seems to be working 0_o Maybe the page was cached in my browser, somehow? That would explain why it was showing the setup completion page without providing credentials.

All seems to be good now. This issue can be closed. Thank you!

**Comment by winxp5421** [comment] 2018-02-16 22:28
Yes, hashtopussy does save cookies in your browser. New install on the same IP/domain name requires you to clear cache for that specific site.

**Comment by lavanoid** [comment] 2018-02-16 22:35
I think to prevent this issue in the future, there should be some checks put in place to verify if an installation has actually been completed or not, rather than relying on a cookie that returns inaccurate results. Something to add to the to-do list.

**Comment by s3inlc** [comment] 2018-02-28 10:48
I'm not really sure what caused this installation issue. Cookies related to the installation procedure are deleted after the installation is successfully completed. So it shouldn't put you directly to the installation complete page even when you run the installation for the second time.
I'll try to reproduce it, maybe there is something other wrong.

**Comment by s3inlc** [comment] 2018-02-28 11:42
I did an installation 0.4.3 and after it completed, I erased all files and did an installation of 0.5.0 at the exact same url. There were no problems.
So in your case did you abort mid-installation and then switched to another version? @lavanoid

**Comment by lavanoid** [comment] 2018-03-01 14:24
I believe I had already completed the installation of 0.4.3 before trying the beta version. I don't think I aborted during mid-installation, however if I come across the problem again I'll open a separate issue with a more in-depth report.

**Comment by s3inlc** [comment] 2018-03-01 14:38
Ok thanks for the feedback. So the original issue is resolved and I'll close the issue.

**Closed by s3inlc** 2018-03-01 14:38 UTC
